### ISSUE TITLE
Add tests / select test framework

### ISSUE THREAD

**Issue by bergren2** [bergren2/README#3]

**Comment by bergren2** [comment]
Not sure how important writing tests is right now, but this might be a good resource for integration tests: https://github.com/simonrice/middleman-rspec

**Comment by bergren2** [comment]
Holding off on this until we upgrade our JS framework.

**Comment by kwpav** [comment]
This should be closed by PR #13. We are using Jest for the test framework as it is built into React.

**Comment by bergren2** [comment]
Sounds good, closing.
